pipeline:
    docker:
        image: plugins/docker
        dockerfile: Dockerfile
        repo: sirboops/nginx
        tags: [1.15.2, latest]
        experimental: true
        squash: true
        secrets: [ docker_username, docker_password ]
